#PowerGrammar 1.0;
!grammar musicplay;
!slot <name:ext>;
!slot <singer:ext>;
!slot <lyric:ext>;
!slot <album:ext>;
!slot <content:ext>;
!slot <songtype>;
!slot <songstyle>;
!slot <songlanguage>;
!rule <song1>;
!rule <song2>;
!rule <endpre>;
!rule <ta>;
!rule <nasong>;
!rule <de>;
!rule <units>;
!rule <unitn>;
!rule <ci>;
!rule <sings>;
!rule <singn>;
!rule <listens>;
!rule <listenn>;
!rule <people>;
!rule <shenme>;
!rule <eps>;
//!slot <poi>;
//!rule <song1>;

!intention <musicplay>;

!modifier <musicplay>: hassing|hassingb|hasplay|haslisten|haslistenb|hasunit|hasunitb|hassong|query|play|sure|can|querysinger|confirm|queryablum|\
playlocalmusic|playwebmusic|querylyric|playalbum|downloadsong|playfavoritelist|clearfavoritelist|queryfavoritelist|invalid|exit|fun|playlocalrandom|newest|hot|playplaylist|clearplaylist|queryplaylist|playranklist;
!modifier <name>: sure|last|confirm;
!modifier <singer>: sure|last|confirm;
!modifier <album>: sure|confirm;
!modifier <songlanguage>: sure;
!modifier <lyric>: sure|confirm;
!modifier <content>: sure|film|prize;
!modifier <songtype>:sure;
!modifier <songstyle>: sure;

!include "CommonInclude.bnh";
!include "MusicPlayInclude.bnh";

!rename<CommonStart>:<CommonStart_>;
<CommonStart>:<CommonStart_>[<yuqicipatch>][那];
<musicplay>:<pattern000>|<pattern000a>|<pattern000d>|\
<pattern001a>|<pattern001b>|<pattern001c>|<pattern001d>|<pattern001e>|<pattern001f>|\
<pattern003a>|<pattern003b>|<pattern003c>|<pattern003ca>|<pattern004>|<pattern004a>|<pattern005>|<pattern006>|\
<pattern100>|<pattern100a>|<pattern100b>|<pattern101>|<pattern101a>|<pattern101b>|<pattern101d>|<pattern101e>|<pattern101f>|<pattern102>|<pattern103>|\
<pattern103s>|<pattern104>|<pattern104s>|<pattern104a>|<pattern105>|<pattern106>|<pattern107>|<pattern107a>|<pattern107b>|<pattern107c>|<pattern107d>|<pattern107e>|<pattern108>|<pattern108c>|<pattern109>|<pattern109a>|\
<pattern200>|<pattern200a>|<pattern200b>|<pattern201>|<pattern201s>|<pattern202>|<pattern203>|<pattern203s>|\
<pattern204>|<pattern204s>|<pattern204a>|<pattern205>|<pattern206>|<pattern207>|<pattern207a>|<pattern208>|<pattern208c>|\
<pattern300>|<pattern300a>|<pattern300s>|<pattern400>|<pattern400a>|<pattern400b>|<pattern401>|<pattern402>|<pattern402s1>|<pattern402s2>|<pattern403>|<pattern404>|<pattern410>|\
<pattern500>|<pattern500a>|<pattern500b>|<pattern500c>|<pattern500d>|<pattern500e>|<pattern500f>|<pattern500g>|\
<pattern501>|<pattern501a>|<pattern501b>|<pattern501c>|<pattern501d>|<pattern501e>|<pattern501f>|<pattern501g>|<pattern501s>|\
<pattern600>|<pattern601>|<pattern601c>|<pattern602>|<pattern603>|<pattern604>|<pattern605>|<pattern606>|\
<pattern600p>|<pattern601p>|<pattern601cp>|<pattern602p>|<pattern603p>|<pattern604p>|<pattern605p>|<pattern606p>|\
<pattern700>|<pattern800>|<pattern800a>|\
<pattern900>|<pattern1000>|<pattern1001>|<pattern1001a>|\
<pattern1002>|<pattern1002a>|<pattern1003>|<pattern1004>|<pattern1004a>|\
<pattern1005>|\
<pattern1006>|<pattern1006a>|<pattern1006b>|\
<pattern1007>|\
<pattern1008>|<pattern1008a>|\
<pattern1009>|<pattern1010>|<pattern1010a>|<pattern1011>|<pattern1012>|<pattern1013>|\
<patternNew>|<patternCan>|<patternCan2>|<patternTalk>|\
<patternExit>;

<patternTalk>:[<tsname>][<tingdun>][让][我们](聊|谈|说)[[一](聊|谈|说)|一下]音乐[怎么样|如何][<endyuqi>];
<shenme:weight=3>:什么|哪些;

<headofdoyouhave>:<Iwanttofind>[[<thatunit>|<unitmusic>]<localmusic>]|<canyoufind>[[<thatunit>|<unitmusic>]<localmusic>]|<Doyouhave>[[<thatunit>|<unitmusic>]<localmusic>]|<localmusic><have>;
//pattern000: [有没有](xx)唱的(歌);
<pattern000>:<CommonStart><headofdoyouhave>[<thatunit>|<unitmusic>]<songexpression>[[<can>]<tolisten>][<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern000a>:<CommonStart>[<thatunit>]<songexpression>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query}>;
//<pattern000b>:(我)(要)(听)<_singer>(的)<song><eps{musicplay!=query&sure}>;
//<pattern000c>:(我)(要)(听)<_name><eps{musicplay!=query&sure}>;
//xx的专辑
<pattern000d>:<CommonStart>[<thatunit>]<singeralbum>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=playalbum&sure}>;

//pattern001: [有没有](歌名);
<pattern001a>:<CommonStart><headofdoyouhave>(<thatunit>|<unitmusic>)[<called><eps{name!=sure}>]\
<_name>的<composedsong>[<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern001b>:<CommonStart><headofdoyouhave>(<thatunit>|<unitmusic>)<song>[<tingdun>]\
[<song>]<called><eps{name!=sure}><_name>[<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern001c>:<CommonStart>[<thatunit>][[<song>]<called><eps{name!=sure}>]\
<_name>[的][<thatunit>]<composedsong>[<tingdun>](<canyoufind>|<Doyouhave>)[<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern001d>:<CommonStart><headofdoyouhave>[[<song>]<called><eps{name!=sure}>]<_name>[的]<thatunit><composedsong>\
[<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern001e>:<CommonStart><headofdoyouhave>[<song>]<called><_name><eps{name!=sure}>[的]\
[<composedsong>][<fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern001f>:<CommonStart><headofdoyouhave>[<unitmusic>|<thatunit>]<composedsong>[<endyuqi><tingdun>]\
[[<song>]<called>]<_name><eps{name!=sure}>[<fullyuqi>]<eps{musicplay!=query&sure}>;

//pattern003: [有没有](xx)[唱]的(歌名);
<pattern003a>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger>\
([演|翻]<sings><eps{musicplay!=sure}>|<singn>)<eps{singer!=sure}>的[<thatunit>][<called><eps{name!=sure}>]<_name>[的]\
[[<thatunit>]<composedsong><eps{musicplay!=sure}>][<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query}>;

<pattern003b>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger>\
<de>[<thatunit>]<composedsong>[<tingdun>][<called><eps{name!=sure}>]<_name>[的][<Doyouhave>|<canyoufind>]\
[<fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern003c>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger>\
<de>[<thatunit>]<_name>\
(的|[的]<thatunit>)<composedsong>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern003ca>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger>\
(<sing>)<eps{singer!=sure}>的[<thatunit>]<_name>\
(的|[的]<thatunit>)<composedsong>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query&sure}>;


//pattern004: [有没有](xx)的歌(歌名);
<pattern004>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger>[<sing><eps{singer!=sure|name!=sure}>]\
的<thatsong>[<tingdun>]<_name>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern004a>:<CommonStart><headofdoyouhave>[<thatunit>|<unitmusic>]<complexsinger>[<sing><eps{singer!=sure|name!=sure}>]\
的[<tingdun>]<_name>[<fullyuqi>]<eps{musicplay!=query}>;

//pattern005: [有没有](xx)的(歌名)的歌;
<pattern005>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger><sing><eps{singer!=sure}>的\
[<song>]<called><eps{name!=sure}><_name>[的]\
[<thatunit>]<composedsong>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern005a>:<CommonStart>[<headofdoyouhave>][<thatunit>|<unitmusic>]<complexsinger><de>\
[<song>]<called><eps{name!=sure}><_name>[的]\
[<thatunit>]<composedsong>[<Doyouhave>|<canyoufind>][<fullyuqi>]<eps{musicplay!=query&sure}>;

//pattern006: [有没有]歌,歌里唱道;
<pattern006>:<CommonStart><headofdoyouhave>[<thatunit>|<unitmusic>]<songwithlyricend>[的][[<tingdun>](<Doyouhave>|<Canyoufind>)][<fullyuqi>]<eps{musicplay!=query&sure}>;

// pattern100: [我][想](听)(歌)
<pattern100>:<CommonStart>([<Iwant>]<complexlistenb>)[<thatunit>|<unitmusic>]<songexpression>[<endyuqi>]<eps{musicplay!=play&sure}>;
// pattern100a: [我][想](听)(本地音乐|歌曲)
<pattern100a>:<CommonStart>([<Iwant>]<complexlistenb>)[<thatunit>|<unitmusic>]<localmusic>[上|里|中][的](<song1>|<song2>)[<endyuqi>]<eps{musicplay!=sure}>;
// pattern100b: [我][想](听)(网络音乐|歌曲)
<pattern100b>:<CommonStart>([<Iwant>]<complexlistenb>)[<thatunit>|<unitmusic>]<web>(<song1>|<song2>)[<endyuqi>]<eps{musicplay!=playwebmusic&sure}>;

// pattern101: [我][想](听)(歌名)
<pattern101>:<CommonStart>([<Iwant>]<complexlistenb>)(<thatunit>|<unitmusic>)[<song><eps{musicplay!=sure}>]<called><eps{name!=sure}>\
<_name>[的<composedsong>][<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;
<pattern101a>:<CommonStart>([<Iwant>]<complexlistenb>)[[<song>]<called><eps{name!=sure}>]<_name>[的]<thatunit>\
<composedsong>[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;
<pattern101b>:<CommonStart>([<Iwant>]<complexlistenb>)[<thatunit>|<unitmusic>][<song>]<called><eps{name!=sure}><_name>的<composedsong>\
[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play}>;
<pattern101d>:<CommonStart>([<Iwant>]<complexlisten>)[<endyuqi>]<song>[<tingdun>][[<song>]<called>]<_name>[<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;
<pattern101e>:<CommonStart>([<Iwant>][在|再][来][给我](<listen>)[[一](下|<listen>)][<thatunit>|<unitmusic>][<songexpression><eps{musicplay!=sure|name!=sure}>])[<tingdun>][<localmusic>]<_name>[<Doyouhave>][<FullYuqi>]<eps{musicplay!=play}>;
<pattern101f>:<CommonStart>([<Iwant>]<complexlisten>)[<endyuqi>]<songwithname>[<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

// pattern102: [我][想](听)(歌)(歌里有....)
<pattern102>:<CommonStart>([<Iwant>]<complexlisten>)<songwithlyricend>[<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;


//pattern103: [我][想](听)(xx)[唱]的[歌名];
<pattern103>:<CommonStart>([<Iwant>]<complexlistena>)<complexsinger>的\
[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play}>;

<pattern103s>:<CommonStart>([<Iwant>]<complexlistena>)<complexsinger>(<sing>)<eps{singer!=sure}>的\
[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern104>:<CommonStart>([<Iwant>]<complexlistenx>)<complexsinger><de>\
[[<song>]<called><eps{name!=sure}>]<_name>[的][<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play}>;

<pattern104s>:<CommonStart>([<Iwant>]<complexlistenx>)<complexsinger><sing><eps{singer!=sure|name!=sure}>的\
[[<song>]<called><eps{name!=sure}>]<_name>[的][[<thatunit>|<unitmusic>]<composedsong>][<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern104a>:<CommonStart>([<Iwant>]<complexlistenx>)<complexsinger><de>\
[[<song>]<called><eps{name!=sure}>]<_name>[的]<thatunit><composedsong>\
[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

//pattern105: [我][想](听)(xx)的(歌)(歌名);
<pattern105>:<CommonStart>([<Iwant>]<complexlistenx>)<complexsinger>[<sing><eps{singer!=sure}>]的<thatsong><_name><eps{name!=sure}>\
[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

//pattern106: [我][想](听)(xx)的(歌名)的歌;
<pattern106>:<CommonStart>([<Iwant>]<complexlistenx>)<complexsinger>[<sing><eps{singer!=sure}>]的[<song>]<called>\
<_name><eps{name!=sure}>[的][<thatunit>]<composedsong>[<tingdun>][<Doyouhave>][<FullYuqi>]<eps{musicplay!=play&sure}>;

// pattern200: [我][想][请][你](帮)(我)(播)(歌)
<pattern200>:<CommonStart>[<Iwantyouhelpme>]<playorsearchMusic>[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=sure}>;

//pattern200a:[我][想][请][你](帮)(我)本地音乐
<pattern200a>:<CommonStart>[<Iwantyouhelpme>]<complexplaya><localmusic>(音乐|歌曲|歌)[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=sure}>;
//pattern200b:[我][想][请][你](帮)(我)网络音乐
<pattern200b>:<CommonStart>[<Iwantyouhelpme>]<complexplaya><web>(<song1>|<song2>)[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=playwebmusic&sure}>;
//换成刘德华的歌
<pattern200c>:<CommonStart>[<Iwantyouhelpme>]<playorsearchMusic>[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=sure}>;

// pattern201: [我][想][请][你](帮)(我)(播)(歌名)
<pattern201>:<CommonStart>[<Iwantyouhelpme>][<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)][<thatunit>|<unitmusic>][<songexpression>][<Fullyuqi>][<tingdun>]\
([<song><eps{musicplay!=sure}>](<called>|名是)<eps{name!=sure}><_name>[的[<thatunit>]<composedsong>]|\
[<song><eps{musicplay!=sure}>][<tingdun>]<_name>)[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=play}>;

<pattern201s>:<CommonStart>[<Iwantyouhelpme>]<complexplay>[<Fullyuqi>][<tingdun>]\
([<song>]<called><eps{name!=sure}><_name>的[<thatunit>]<composedsong>|\
<_name><thatunit><composedsong>)[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=play&sure}>;

// pattern202: [我][想][请][你](帮)(我)(播)(歌)(歌里有....)
<pattern202>:<CommonStart>[<Iwantyouhelpme>]<complexplay><songwithlyricend>[<tingdun>][<FullYuqi>]<eps{musicplay!=play&sure}>;

// pattern204: [我][想][请][你](帮)(我)(播)(xx)唱的(歌名);
<pattern203>:<CommonStart>[<Iwantyouhelpme>]<complexplaya><complexsinger>\
的[<tingdun>][<FullYuqi>]<eps{musicplay!=play}>;
<pattern203s>:<CommonStart>[<Iwantyouhelpme>]<complexplaya><complexsinger><sing><eps{singer!=sure}>\
的[<tingdun>][<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern204>:<CommonStart>[<Iwantyouhelpme>][<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)][<thatunit>|<unitmusic>][<composedsong>|<songwithlyric>|<zhutiqu>|<huojiang>]<complexsinger>\
<de>[(<song><eps{musicplay!=sure}>)][<called><eps{name!=sure}>]<_name>[<tolisten>][<tingdun>][<endyuqi>]<eps{musicplay!=play}>;
<pattern204s>:<CommonStart>[<Iwantyouhelpme>]<complexplayx><complexsinger><sing><eps{singer!=sure|name!=sure}>\
的[<song>][<called><eps{name!=sure}>]<_name>[<tolisten>][<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;

<pattern204a>:<CommonStart>[<Iwantyouhelpme>]<complexplayx><complexsinger>[<sing><eps{singer!=sure|name!=sure}>]\
<de>[<song>][<called><eps{name!=sure}>]<_name>[的]\
<thatunit><composedsong>[<tolisten>][<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;

// pattern205: [我][想][请][你](帮)(我)(播)(xx)的歌(歌名);
<pattern205>:<CommonStart>[<Iwantyouhelpme>]<complexplayx><complexsinger>[<sing>]<de><thatsong><_name><eps{name!=sure}>\
[<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;

// pattern206: [我][想][请][你](帮)(我)(播)(xx)的(歌名)那首歌;
<pattern206>:<CommonStart>[<Iwantyouhelpme>]<complexplayx><complexsinger>[<sing>]的[<song>]<called><_name><eps{name!=sure}>\
[的][<thatunit>]<composedsong>\
[<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;

//专辑
//pattern107: [我][想](听)[xx的](专辑)(专辑名);
<pattern107>:<CommonStart>([<Iwant>](<complexlistenb>))[<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure|album!=sure}>]的](<album><eps{album!=sure}>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)[(里[面]|中|内)的<song>][<FullYuqi>]<eps{musicplay!=playalbum&sure}>;
<pattern107a>:<CommonStart>([<Iwant>](<complexlistenb>))[<thatunit>|<unitmusic>]专辑[<tingdun>]<complexsinger>[出<eps{singer!=sure|album!=sure}>]<de><album>[(里[面]|中|内)的<song>][<FullYuqi>]<eps{musicplay!=playalbum&sure}>;

//我想听XX的专辑
<pattern107b>:<CommonStart>(([<Iwant>](<complexlistenb>|列出|<change>))|([<Iwantyouhelpme>](<complexplayb>|<change>)))[<thatunit>|<unitmusic>]<complexsinger><eps{singer!=sure}>[出|发行|发布]的[(所有|全部|个人)[的]](专)(辑)[<tingdun>][<FullYuqi>]<eps{musicplay!=playalbum&sure}>;
<pattern107c>:<CommonStart>(<Iwanttofind>|<canyoufind>|<Doyouhave>)[<thatunit>|<unitmusic>]<complexsinger><eps{singer!=sure}>[出|发行|发布]的[(所有|全部|个人)[的]](专)(辑)[<tingdun>][<FullYuqi>]<eps{musicplay!=playalbum&sure}>;
<pattern107d>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<complexsinger><eps{singer!=sure}>[出|发行|发布]的[(所有|全部|个人)[的]](专)(辑)[还|都]有(<shenme>|(些)<shenme>)<eps{singer!=sure}>[<Fullyuqi>]<eps{musicplay!=playalbum&sure}>;
<pattern107e>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[还|都](有|<sing>过)(<shenme>|(些)<shenme>)(专)(辑)<eps{singer!=sure}>[<Fullyuqi>]<eps{musicplay!=playalbum&sure}>;

//pattern108: [我][想](听)[xx的](专辑)(专辑名)里的那首歌名;
<pattern108>:<CommonStart>([<Iwant>](<complexlistenb>|<change>))[<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure|album!=sure}>]的][<thatunit>](<album><eps{album!=sure}>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)(里[面]|中|内)[的]\
[<thatsong>]<_name><eps{name!=sure}>[[<thatunit>]<composedsong>][<tingdun>][<endyuqi>]<eps{musicplay!=play&sure}>;
<pattern108c>:<CommonStart>([<Iwant>](<complexlistenb>|<change>))[<thatunit>|<unitmusic>]<album>(里[面]|中|内)的\
[<thatsong>]<_name>[[<thatunit>]<composedsong>][<tingdun>][<endyuqi>]<eps{musicplay!=play}>;

//专辑(专辑名)中有哪些歌曲
<pattern109>:<CommonStart>[那][请问][<complexask>]专辑<album{album!=sure}>[里[面]|中|内][还|都](有)(<shenme>|(些)<shenme>)<song>[<Fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern109a>:<CommonStart>[那][请问][<complexask>]<album{album!=sure}>专辑[里[面]|中|内][还|都](有)(<shenme>|(些)<shenme>)<song>[<Fullyuqi>]<eps{musicplay!=query&sure}>;

//专辑
//pattern207: [我][想][请][你](帮)(我)(播)[xx的](专辑)(专辑名);
<pattern207>:<CommonStart>[<Iwantyouhelpme>](<complexplayb>)[<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure|album!=sure}>]的][<thatunit>](<album{album!=sure}>[(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)[(里[面]|中|内)的<song>]\
[<tingdun>][<endyuqi>]<eps{musicplay!=playalbum&sure}>;
<pattern207a>:<CommonStart>[<Iwantyouhelpme>](<complexplayb>|<change>)[<thatunit>|<unitmusic>]专辑[<tingdun>]<complexsinger>[出<eps{singer!=sure|album!=sure}>]的<album>[(里[面]|中|内)的<song>][<tingdun>][<endyuqi>]<eps{musicplay!=playalbum&sure}>;

//pattern208: [我][想][请][你](帮)(我)(播)[xx的](专辑)(专辑名)里的那首歌名;
<pattern208>:<CommonStart>[<Iwantyouhelpme>](<complexplayb>|<change>)[<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure}>]的][<thatunit>](<album>[(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)(里[面]|中|内)[的]\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong><eps{musicplay!=sure}>][<tingdun>][<endyuqi>]<eps{musicplay!=play}>;
<pattern208c>:<CommonStart>[<Iwantyouhelpme>](<complexplayb>|<change>)[<thatunit>|<unitmusic>]<album>(里[面]|中|内)的\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong><eps{musicplay!=sure}>][<tingdun>][<endyuqi>]<eps{musicplay!=play}>;


//misc
//pattern300: 来点...
<pattern300>:<CommonStart>[<tsname>][<tingdun>][请][你](随便|随机)(<play>|来)[一]<unitmusic>[<song>]<eps{musicplay!=sure}>[[(给|为)我]<listen>[[一](<listen>|下)]][<Fullyuqi>]<eps{musicplay!=playlocalrandom}>;
<pattern300a>:<CommonStart>[<tsname>][<tingdun>][<Iwant>]随便<listen>[一]<unitmusic><song><eps{musicplay!=sure}>[<Fullyuqi>]<eps{musicplay!=playlocalrandom}>;
<pattern300s>:<CommonStart>[<tsname>][<tingdun>][请[随便|随机]|随便|随机|<Iwant>]<play>[一]<unitmusic>((<pleasure>|<songstyle{songstyle!=sure}>)的|<pleasure>的<composedsong>)[<Fullyuqi>]<eps{musicplay!=playlocalrandom&sure}>;

//pattern400:他有没有[唱过]歌名[]
<pattern400>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[有[没有]]<sing>过[<called>]<_name>[[的][<thatunit>]<song><eps{name!=sure}>]\
[呢|吗|啊|呀]<eps{musicplay!=confirm&sure|singer!=sure|name!=confirm}>;
<pattern400a>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[有[没有]]<sing>过[<called>]<album{album!=sure}>[的][(这|那)(个|张|首)]专辑\
[呢|吗|啊|呀]<eps{musicplay!=confirm&sure|singer!=sure|album!=confirm}>;
<pattern400b>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[有[没有]]<sing>过[<called>]<lyric{lyric!=sure}>[的][(这|那)(句|段|个)]<geci>\
[呢|吗|啊|呀]<eps{musicplay!=confirm&sure|singer!=sure|lyric!=confirm}>;

<pattern401>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[有[没有]]<sing>过<thatunit>[<called>]<_name>[的<song><eps{name!=sure}>]\
[呢|吗|啊|呀]<eps{musicplay!=confirm&sure|singer!=sure|name!=confirm}>;
<pattern402>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)<eps{singer!=sure}>有(没有)一<unitmusic>\
<_name><eps{name!=sure&confirm}>[<fullyuqi>]<eps{musicplay!=confirm}>;
<pattern402s1>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)<eps{singer!=sure}>有(没有)一<unitmusic><song>[<tingdun>]\
[<called>]<_name><eps{name!=sure&confirm}>[<fullyuqi>]<eps{musicplay!=confirm&sure}>;
<pattern402s2>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)<eps{singer!=sure}>有(没有)一<unitmusic>\
[<called>]<_name><eps{name!=sure&confirm}>的<song>[<fullyuqi>]<eps{musicplay!=confirm&sure}>;

<pattern403>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)[还|都](有|<sing>过)(<shenme>|(些)<shenme>)<song><eps{singer!=sure}>\
[<Fullyuqi>]<eps{musicplay!=query&sure}>;
<pattern404>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<ta{singer!=last}>|<complexsinger>)的<song>[还|都]有(<shenme>|(些)<shenme>)<eps{singer!=sure}>\
[<Fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern410>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]哪<unitmusic><song>[[的](歌)(词)]里[面](有|唱(到|道))[(歌)(词)][<tingdun>]<lyric>[的歌词][<endyuqi>]<eps{musicplay!=query&sure}><eps{lyric!=sure}>;


<patternNew>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>][<newest>]<complexsinger>[<newest>](有[没有]|又)([出[了]][<shenme>]新[的]|新出[了][<shenme>])\
(歌|作品|作|专辑|唱片)[<Fullyuqi>]<eps{musicplay!=query&sure|singer!=sure}>;

<patternCan>:<eps{musicplay!=can&sure}><CommonStart>[<tsname>][<tingdun>][那|难道](你[真的](<can>|会[不会])[<help>我](<play>|<searchmusic>)<song>|(<play>|<searchmusic>)<song>你(<can>|会[不会]))[<Fullyuqi>];
<patternCan2>:<eps{musicplay!=can&sure}><CommonStart>[<tsname>][<tingdun>][你]有(<play>|<searchmusic>)<song>的(能力|本领|功能)[<Fullyuqi>];

//pattern500:歌名是谁唱的
<pattern500>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<nasong{name!=last}>|[<thatunit>]<called><_name><eps{name!=sure}>的[<thatunit>]<song>|\
|<_name><eps{name!=sure}>[<thatunit><song>]|<zhutiqu>)[<afterall>][是]<whichpeople><sing>的[<Fullyuqi>]<eps{musicplay!=querysinger&sure}>;
<pattern500a>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>](<nasong{name!=last}>|[<thatunit>]<called><_name><eps{name!=sure}>的[<thatunit>]<song><eps{musicplay!=querysinger&sure}>|\
|<_name><eps{name!=sure}>[<thatunit><song><eps{musicplay!=sure}>]<eps{musicplay!=querysinger}>)[<afterall>][是]<whichpeople>的[<Fullyuqi>];
//pattern500b: 谁唱过歌名
<pattern500b>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<whichpeople><sing>[过](<nasong{name!=last}>|[<thatunit>]<called><_name><eps{name!=sure}>的[<thatunit>]<song>|\
|<_name><eps{name!=sure}>[<thatunit><song>]|<zhutiqu>)[<Fullyuqi>]<eps{musicplay!=querysinger&sure}>;
//pattern500c:谁唱过歌词里有送你离开的歌|谁的歌里有送你离开这个歌词
<pattern500c>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<whichpeople><sing>过<geci>(里[面]|[当]中|内)有<lyric>的(<song1>|<song2>)[<Fullyuqi>]<eps{musicplay!=querysinger&sure}><eps{lyric!=sure}>;
<pattern500d>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<whichpeople>的(<song1>|<song2>)(里[面]|[当]中|内)有<lyric><that>[个|句]<geci>[<Fullyuqi>]<eps{musicplay!=querysinger&sure}><eps{lyric!=sure}>;
//专辑名是谁唱的
<pattern500e>:[那][请问][<Youknow>|<Doyouknow>]<album><eps{album!=sure}>[(这|那)(个|张)]专辑[<afterall>][是]<whichpeople><sing>的[<Fullyuqi>]<eps{musicplay!=querysinger&sure}>;
<pattern500f>:[那][请问][<Youknow>|<Doyouknow>][(这|那)(个|张)][专辑]<called><album><eps{album!=sure}>的专辑[是]<whichpeople><sing>的[<Fullyuqi>]<eps{musicplay!=querysinger&sure}>;
<pattern500g>:[那][请问][<Youknow>|<Doyouknow>]<album><eps{album!=sure}>[<afterall>][是]<whichpeople>的专辑[<Fullyuqi>]<eps{musicplay!=querysinger&sure}>;
//歌名是歌手唱的吗
<pattern501>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name><eps{name!=confirm}>[(这|那)(个|张|首)][(<song1>|<song2>)<eps{name!=sure&confirm}>]))[<afterall>]是不是<complexsinger>[<sing><eps{musicplay!=sure}>](的)[(<song1>|<song2>)<eps{musicplay!=sure}>][<fullyuqi>]<eps{musicplay!=confirm|singer!=sure}>;
<pattern501a>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name><eps{name!=confirm}>[(这|那)(个|张|首)][(<song1>|<song2>)<eps{name!=sure&confirm}>]))[<afterall>]是<complexsinger>[<sing><eps{musicplay!=sure}>](的)[(<song1>|<song2>)<eps{musicplay!=sure}>]<questionyuqi><eps{musicplay!=confirm|singer!=sure}>;
//专辑名是歌手唱的吗
<pattern501b>:<CommonStart>[那][请问]<album><eps{album!=confirm&sure}>[(这|那)(个|张|首)](专)(辑)[<afterall>]是不是<complexsinger>[<sing><eps{musicplay!=sure}>](的)[(<song1>|<song2>)<eps{musicplay!=sure}>][<fullyuqi>]<eps{musicplay!=confirm|singer!=sure}>;
<pattern501c>:<CommonStart>[那][请问]<album><eps{album!=confirm&sure}>[(这|那)(个|张|首)](专)(辑)[<afterall>]是<complexsinger>[<sing><eps{musicplay!=sure}>](的)[(<song1>|<song2>)<eps{musicplay!=sure}>]<questionyuqi><eps{musicplay!=confirm|singer!=sure}>;
//歌名是专辑名中的歌吗
<pattern501d>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name>[(这|那)(个|首)][(<song1>|<song2>)<eps{name!=sure}>]))<eps{name!=confirm}>[<afterall>]是不是<album>[(这|那)(个|张)](专)(辑)[[里[面]|[当]中|内]]<eps{album!=sure}>(的)[(<song1>|<song2>)][<fullyuqi>]<eps{musicplay!=sure&confirm}>;
<pattern501e>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name>[(这|那)(个|首)][(<song1>|<song2>)<eps{name!=sure}>]))<eps{name!=confirm}>[<afterall>]是不是(专)(辑)<album>[[里[面]|[当]中|内]]<eps{album!=sure}>(的)[(<song1>|<song2>)][<fullyuqi>]<eps{musicplay!=sure&confirm}>;
<pattern501f>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name>[(这|那)(个|首)][(<song1>|<song2>)<eps{name!=sure}>]))<eps{name!=confirm}>[<afterall>]是<album>[(这|那)(个|张)](专)(辑)[[里[面]|[当]中|内]]<eps{album!=sure}>(的)[(<song1>|<song2>)]<questionyuqi><eps{musicplay!=sure&confirm}>;
<pattern501g>:<CommonStart>[那][请问](<nasong{name!=last}>|(<_name>[(这|那)(个|首)][(<song1>|<song2>)<eps{name!=sure}>]))<eps{name!=confirm}>[<afterall>]是(专)(辑)<album>[[里[面]|[当]中|内]]<eps{album!=sure}>(的)[(<song1>|<song2>)]<questionyuqi><eps{musicplay!=sure&confirm}>;

<pattern501s>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]([<thatunit>]<called><_name>的[<thatunit>]<song><eps{name!=sure}>|\
|<_name><eps{name!=sure}><thatunit><song>|<zhutiqu>)[<afterall>]是[不是]<complexsinger>[<sing>](的)[<song1>|<song2>][<fullyuqi>]<eps{musicplay!=confirm&sure|singer!=sure&confirm}>;

<IwanttoListen>:[[我][<now>][突然][就][<very>][<want>]]<complexlistenb>|[<can>][<please>[你]]<complexplayb>[[[一]<unitmusic>][来|了]<listen>[[一](下|<listen>)]];

<pattern600>:<CommonStart><Imtold>[][有][<thatunit>|<unitmusic>]<songexpression><bePoplular>[<Fullyuqi>]<eps{musicplay!=query&sure}>;

<pattern600p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>]<songexpression>[<tingdun>][<zuijin>]<bePoplular>[<Fullyuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern601>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<song><eps{musicplay!=sure}>]\
(<called><eps{name!=sure}><_name>[的][<thatunit>][<song>]|\
<_name>[<thatunit><song><eps{name!=sure}>])[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=query}>;

<pattern601p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<song><eps{musicplay!=sure}>]\
(<called><eps{name!=sure}><_name>[的][<thatunit>][<song>]|\
<_name>[<thatunit><song><eps{name!=sure}>])[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern601c>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>](<complexsinger>[这[一](位|个)<people>]|[有[一](位|个)]<people><complexsinger>)\
[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=query&sure}>;

<pattern601cp>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>](<complexsinger>[这[一](位|个)<people>]|[有[一](位|个)]<people><complexsinger>)\
[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern602>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<song>]<complexsinger>[<sing><eps{singer!=sure|name!=sure}>]\
<de>[<song>][<called><eps{name!=sure}>]<_name>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=query&sure}>;

<pattern602p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<song>]<complexsinger>[<sing><eps{singer!=sure|name!=sure}>]\
<de>[<song>][<called><eps{name!=sure}>]<_name>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern603>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有]<complexsinger>[<sing>]的<thatsong><_name><eps{name!=sure}>[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=query&sure}>;

<pattern603p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有]<complexsinger>[<sing>]的<thatsong><_name><eps{name!=sure}>[<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern604>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure|album!=sure}>]的]\
(<album>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)[(里[面]|中|内)的<song>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=query&sure}>;

<pattern604p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure|album!=sure}>]的]\
(<album>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)[(里[面]|中|内)的<song>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern605>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure}>]的]\
(<album>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)(里[面]|中|内)的\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern605p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>][<complexsinger>[出<eps{singer!=sure}>]的]\
(<album>[的|(这|那)(个|张)]专辑|[<zuopinmodify>]专辑<album><eps{album!=sure}>)(里[面]|中|内)的\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern606>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>]<album>(里[面]|中|内)的\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern606p>:<CommonStart>[<zuijin>]<Imtold>[<zuijin>][有][<thatunit>|<unitmusic>]<album>(里[面]|中|内)的\
[<thatsong>]<_name><eps{name!=sure}>[的][[<thatunit>]<composedsong>][<tingdun>][<zuijin>]<bePoplular>[<FullYuqi>][<tingdun>]\
<IwanttoListen>[<FullYuqi>]<eps{musicplay!=play&sure}>;

<pattern700>:<CommonStart>[<Complexask>][<complexsinger>[<sing>]<de>[<thatsong>]]<_name>(好不好听|好听吗|是(不是|否)[很]好听)[<complexask2>][<fullyuqi>]<eps{musicplay!=query&sure}>;

//pattern800: 东风破出自周杰伦的哪张专辑？东风破是周杰伦的哪张专辑里的歌？
<pattern800>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<_name><eps{name!=sure}><fromablum><_singer><eps{singer!=sure}>[的](哪|那)([一](个|张))专辑[[(里[面]|中|内)]的[<song>]][<fullyuqi>]<eps{musicplay!=queryablum&sure}>;
<pattern800a>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>]<_name><eps{name!=sure}><fromablum>(哪|那)([一](个|张))专辑[[(里[面]|中|内)]的[<song>]][<fullyuqi>]<eps{musicplay!=queryablum&sure}>;

//pattern900:月亮之上的歌词是什么
<pattern900>:<CommonStart>[那][请问][<Youknow>|<Doyouknow>|<tellmemore>]<_name><eps{name!=sure}>的歌词[是<shenme>]<eps{musicplay!=querylyric&sure}>;

//pattern1000:你会播什么歌
<pattern1000>:<eps{musicplay!=play&sure}><CommonStart>[<tsname>][<tingdun>][那][你](<can>|会[不会])<play>(什么|啥)<song>[<Fullyuqi>];

//下载音乐
<pattern1001>:<CommonStart>[<helpme>|<iwantto>]下[载]<song>[<Fullyuqi>]<eps{musicplay!=downloadsong&sure}>;
<pattern1001a>:<CommonStart>[<helpme>|<iwantto>]<song>下载[<Fullyuqi>]<eps{musicplay!=downloadsong&sure}>;

//播放我的收藏列表
<pattern1002>:<CommonStart>[<Iwant>](<complexlistenb>|打开)<favoritelist>[<Fullyuqi>]<eps{musicplay!=playfavoritelist&sure}>;
<pattern1002a>:<CommonStart>[<Iwantyouhelpme>](<complexplaya>|打开)([我](收)(藏)的<song>|<favoritelist>)[<tolisten>][<FullYuqi>][<Fullyuqi>]<eps{musicplay!=playfavoritelist&sure}>;

//清空收藏列表
<pattern1003>:<CommonStart>[<Iwantyouhelpme>]清空<favoritelist>[<FullYuqi>][<Fullyuqi>]<eps{musicplay!=clearfavoritelist&sure}>;

//查看收藏列表
<pattern1004>:<CommonStart>[<Iwantyouhelpme>](查(看|询)|显示|列出)([我](收)(藏)的<song>|<favoritelist>)[<FullYuqi>]<eps{musicplay!=queryfavoritelist&sure}>;
//我收藏了什么歌
<pattern1004a>:<CommonStart>[最近][我]<add>[了|过](什么|哪些)<song>[(进|到|入)<favoritelist>][<Fullyuqi>]<eps{musicplay!=queryfavoritelist&sure}>;

//帮我换XXX的歌|专辑
<pattern1005>:<CommonStart>[<Iwantyouhelpme>](换[成|[一]<unitmusic>])<singerssong>[<FullYuqi>]<eps{musicplay!=play&sure}>;


//最近有什么好听的歌
<pattern1006>:<CommonStart>最近(有|流行)什么[好听的][新]<song>[<FullYuqi>]<eps{musicplay!=play&newest&sure}>;
//来点新歌
<pattern1006a>:<CommonStart>([<iwantto>|<helpme>](来)(点)|[<iwantto>]<listen>|[<helpme>|<iwantto>]<play>)[一][<unitmusic>]<newest>[比较][热门的][网络]<song>[<FullYuqi>]<eps{musicplay!=play&newest&sure}>;
//给我推荐几首音乐
<pattern1006b>:<CommonStart>[<helpme>](推荐|来|给[我])[一|几]<unitmusic><song>[<tolisten>][<FullYuqi>]<eps{musicplay!=play&newest&sure}>;

//来点好听的
<pattern1007>:<CommonStart>[<helpme>](<play>[[一]<unitmusic>])[比较](<pleasure>(的)|(热)(门)(的))[[网络]<song>][<FullYuqi>]<eps{musicplay!=play&hot&sure}>;

//播放我的播放列表
<pattern1008>:<CommonStart>[<Iwant>](<complexlistenb>|打开)<playlist>[<Fullyuqi>]<eps{musicplay!=playplaylist&sure}>;
<pattern1008a>:<CommonStart>[<Iwantyouhelpme>](<complexplaya>|打开)<playlist>[<tolisten>][<FullYuqi>]<eps{musicplay!=playplaylist&sure}>;

//清空播放列表
<pattern1009>:<CommonStart>[<Iwantyouhelpme>]清空<playlist>[<Fullyuqi>]<eps{musicplay!=clearplaylist&sure}>;

//查看播放列表
<pattern1010>:<CommonStart>[<Iwantyouhelpme>](查(看|询)|显示|列出)<playlist>[<Fullyuqi>]<eps{musicplay!=queryplaylist&sure}>;
//我听过什么歌
<pattern1010a>:<CommonStart>[最近][我]<listen>[了|过](什么|哪些)<song>[<Fullyuqi>]<eps{musicplay!=queryplaylist&sure}>;

//放这首歌给我听
<pattern1011>:<CommonStart>[<Iwantyouhelpme>]<playorsearch><that><eps{name!=last}>[<unitmusic>]<song>[<tolisten>][<tingdun>][<FullYuqi>]<eps{musicplay!=sure}>;
//影视歌曲排行榜
<pattern1012>:<CommonStart>[<Iwanttofind>|<canyoufind>|<Doyouhave>|[<Iwantyouhelpme>]<play>|[<iwantto>]<listen>]<songranklist>[<FullYuqi>]<eps{musicplay!=playranklist&sure&sure}>;

//我要听专辑
<pattern1013>:<CommonStart>([<Iwant>]<complexlistenb>)[<thatunit>|<unitmusic>]专辑[<endyuqi>]<eps{musicplay!=playalbum&sure}>;

<patternExit>:[<generalHead>][算了[吧]][<tingdun>][<tsname>][<tingdun>][算了[吧]][<tingdun>]\
([<stop>][<tingdun>][<now>][我][<now>][突然]不[<want>](<listen>|<play>)[<_singer>[的]][<song>]了)[<tingdun>](<pattern100>|<pattern103>)[<endyuqi>];

<fromablum>:((出|来)(自[于]|于|源[于]))|(是);
<singerssong>:(<complexsinger>|<ta{singer!=last}>)[<sing><eps{singer!=sure}>]的[<thatunit>]<composedsong>|\
(<songlanguage{songlanguage!=sure}>[的]<people><eps{songlanguage!=sure}>)[<sing>]的<composedsong>;

<singeralbum>:(<complexsinger>|<ta{singer!=last}>)[<sing><eps{singer!=sure}>]的[<thatunit>](专)(辑);

<songwithlyric>:[<complexsinger>[<sing>]的][<thatunit>](<song1><ci>[里[面]|中]|里面)<contain><lyric>[这[个]词]<eps{lyric!=sure}>的[<thatunit>]<composedsong>;
<songwithlyricend>:<composedsong>[,][那[首]][<composedsong>]\
([里[面]]有(这)(么(几句)|些)[[<song1>]<ci>]|[<song1>][里[面]](是)(这么)(唱)(的)|<song1>[<ci>]里[面]有|<song1>[<ci>]里[面]唱(道|到))\
[,|:]<lyric><eps{lyric!=sure}>[的];
<songwithname>:[<song1>]名(叫|是)<_name><eps{name!=sure}>的[<thatunit>]<composedsong>;

<songexpression>:[<localmusic>](<composedsong>|<singerssong>|<songwithlyric>|<zhutiqu>|<huojiang>);

<zhutiqu>:[<complexsinger>[<sing>]的][<thatunit>][电影<eps{content!=sure&film}>]<content>的((主)(题)|(片)(尾)|(片)(头))<song>;

<huojiang>:([<complexsinger>[<sing><eps{singer!=sure}>]的][<thatunit>]<content>\
[的][<newest>][的](获)(奖)[的](<song>|作品|作)|\
[<complexsinger>[<sing><eps{singer!=sure}>]的][<thatunit>][<newest>][的]获[得]\
<content><eps{content!=sure&prize}>奖的(<song>|作品));

<composedsong>:[那[种]][[<songlanguage{songlanguage!=sure}>[的]](<songtypeall><eps{songtype!=sure}>|<songstyle{songtype!=sure}>|<songlanguage{songlanguage!=sure}>)[类[型]|风格|主题]][的][老]<song>|\
[那[种]]<songtypeall><eps{songtype!=sure}>[的][(<songstyle{songtype!=sure}>|<songlanguage{songlanguage!=sure}>)]<song>|\
[那[种]](<songtypestandalone><eps{songtype!=sure}>[类[型]|风格|主题]|<songtypeprefix><eps{songtype!=sure}>(类[型]|风格|主题))[的];
<complexlisten>:[在|再][来][给我](<listen>)[[一](下|<listen>)][<thatunit>|<unitmusic>][<songexpression>];
<complexplay>:[<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)][<thatunit>|<unitmusic>][<songexpression>];
<playorsearchMusic>:<playorsearch>[<thatunit>|<unitmusic>]<songexpression>;
<playorsearch>:[<can>][在|再][来][<helpme>][再|在](<play><eps{musicplay!=play}>|<searchmusic><eps{musicplay!=query}>)[[一](下)];
<complexlistenx>:[在|再][来][给我](<listen>)[[一](下|<listen>)][<thatunit>|<unitmusic>]\
[<composedsong>|<songwithlyric>|<zhutiqu>|<huojiang>];
<complexplayx>:[<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)][<thatunit>|<unitmusic>][<composedsong>|<songwithlyric>|<zhutiqu>|<huojiang>];

<complexlistena>:[在|再][来][给我](<listen>)[[一](下|<listen>)][<thatunit>|<unitmusic>][<composedsong>];
<complexplaya>:[<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)][<thatunit>|<unitmusic>][<composedsong>];

<complexlistenb>:[在|再][来][给我](<listen>)[[一](下|<listen>)];
<complexplayb>:[<can>][在|再][来][<helpme>][再|在](<play>)[[一](下)];

<thatsong>:[<thatunit>]<composedsong>|<composedsong>[<tingdun>][那首|名叫|<song>名(是|叫[作|做])];

<endyuqici>:呢|啊|呀|吧|吗|耶|哟|唷|哇|啦|嘛|哦|噢;
<questionyuqi>:吗;
<endpre>:好[不好]|可[以][不可以]|行[不行]|怎[么]样|如何|(谢|多)谢[你][了];
<endyuqi>:<endpre>|<endyuqici>|<endpre><questionyuqi>;

<Iwant>:[<tsname>][<tingdun>][<now>][我][<now>][突然][还][就][<very>][<want>][再|在];
<Iwantyouhelpme>:[<tsname>][<tingdun>][<now>][我][<now>][就][<very>][<want>][<can>][<please>][你][<help><me>];
<pleasure>:(好)(听)|(悦)(耳)|(动)(听);
<de:weight=-1>:的;

<complexsinger>:[关于<eps{musicplay!=fun}>][<localmusic>][那[位|个]][歌手][[名]叫]<_singer>[的][那[位|个]][歌手|家伙|小伙[子]|小子|美女]|<ta><eps{singer!=last}>;

<whichpeople>:((谁)|(哪(个|位)<people>));
<geci>:歌词;
<web>:在线|网络[上][的];
<whatsong>:(((哪|那)些)|(什么))(<song1>|<song2>);
<change>:换[成];
<yuqicipatch>:[真|好|太]无聊[了][<fullyuqi>];
//主题/获奖